// Nav + Footer mount for service subpages (paths relative to /services/)
document.querySelectorAll('img').forEach(function(i){i.addEventListener('error',function(){i.style.display='none'});if(i.complete&&i.naturalWidth===0)i.style.display='none'});
function mountChrome(p){
var n=document.getElementById('nav-host'),f=document.getElementById('footer-host');
if(n){n.innerHTML='<nav class="nav"><div class="nav-inner"><a href="../index.html" class="nav-brand"><img src="../img/logo-header.png" alt="Dental Den Logo" class="nav-logo"></a><div class="nav-links" id="mobile-nav-links"><a href="../index.html" data-page="home">Home</a><a href="../services.html" data-page="services">Services</a><a href="../about.html" data-page="about">About</a><a href="../blog.html" data-page="blog">Blog</a><a href="../contact.html" data-page="contact">Contact</a></div><a href="../contact.html" class="nav-cta">Book a visit \u2192</a><div class="nav-mobile-toggle" id="nav-toggle"><span></span><span></span><span></span></div></div></nav>';
var t=n.querySelector('#nav-toggle'),m=n.querySelector('#mobile-nav-links');
if(t)t.addEventListener('click',function(){t.classList.toggle('open');m.classList.toggle('open')});
var l=n.querySelectorAll('.nav-links a');for(var i=0;i<l.length;i++)if(l[i].getAttribute('data-page')===p)l[i].classList.add('active');}
if(f){var y=new Date().getFullYear();f.innerHTML='<footer class="ftr"><div class="wrap"><div class="ftr-grid"><div class="ftr-brand"><img src="../img/logo.png" alt="Dental Den Logo" style="height:90px;width:auto;margin-bottom:14px;filter:brightness(0) invert(1)"><p>A modern boutique multi-speciality dental practice in Andheri West, Mumbai. Serving patients from Lokhandwala, Oshiwara, and Kandivali. Led by Dr. Tanya Kusum.</p></div><div class="ftr-col"><h5>Visit</h5><p>Marble Arch, Shastri Nagar<br>Andheri West, Mumbai 400053</p><p>Mon\u2013Sat \u00b7 10am \u2013 9pm</p></div><div class="ftr-col"><h5>Reach</h5><a href="tel:+917208909768">+91 72089 09768</a><a href="https://wa.me/917208909768">WhatsApp</a><a href="mailto:hello@dentalden.in">hello@dentalden.in</a></div><div class="ftr-col"><h5>Practice</h5><a href="../index.html">Home</a><a href="../services.html">All services</a><a href="../about.html">About Dr. Tanya</a><a href="../blog.html">Journal & Insights</a><a href="../contact.html">Book a visit</a></div></div><div class="ftr-bottom"><div>\u00a9 '+y+' Dental Den \u00b7 Andheri West, Mumbai</div><div>Serving Andheri West \u00b7 Lokhandwala \u00b7 Oshiwara \u00b7 Kandivali</div></div></div></footer>';}}
mountChrome('services');
